export const styles = {
  landingPage: {
    width: "auto",
    height: "3306px",
    flexGrow: 0,
    backgroundColor: "#f8f9ff",
  },
  header: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "auto",
    height: "40px",
    padding: "9px 121px",
    backgroundImage: "linear-gradient(to right, #39c6ef 0%, #92cb76 109%)",
  },
  headerContent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px",
    gap: "640px",
    width: "1198px",
    height: "22px",
  },
  headerLeft: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "21px",
    width: "315px",
    height: "22px",
    flex: "none",
    order: 0,
    flexGrow: 0,
  },
  headerRight: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "8px",
    width: "243px",
    height: "20px",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  headerContact: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "8px",
    width: "130px",
    height: "20px",
    flex: "none",
    order: 0,
    flexGrow: 0,
  },
  headerContactNum: {
    width: "auto",
    height: "20px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    display: "flex",
    alignItems: "center",
    color: "#FFFFFF",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  headerEmail: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "8px",
    width: "142px",
    height: "20px",
    flex: "none",
    order: 2,
    flexGrow: 0,
    marginLeft: "-10px",
  },
  headerLeftDivider: {
    boxSizing: "border-box",
    width: "1px",
    height: "22px",
    borderLeft: "1px solid #FFFFFF",
    borderRadius: "8px",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  headerEmailAdd: {
    width: "118px",
    height: "20px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    display: "flex",
    alignItems: "center",
    color: "#FFFFFF",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  headerCalendar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "8px",
    width: "243px",
    height: "20px",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  headerCalendarData: {
    width: "219px",
    height: "20px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    display: "flex",
    alignItems: "center",
    color: "#FFFFFF",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  tickertape: {
    position: "absolute",
    width: "100%",
    height: "40px",
    left: "0px",
    top: "auto",
    background: "#D3080D",
    mixBlendMode: "normal",
  },
  tickertapeContent: {
    position: "absolute",
    width: "auto",
    height: "20px",
    left: "calc(50% - 1382px/2)",
    top: "calc(50% - 20px/2)",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "20px",
    display: "flex",
    alignItems: "center",
    color: "#FFFFFF",
  },
  navbar: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "239px",
    position: "absolute",
    width: "1440px",
    height: "56px",
    left: "120px",
    top: "120px",
    paddingRight: "15px",
  },
  navigation: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "413px",
    height: "35px",
    gap: "14px",
    marginLeft: "150px",
  },
  register: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "0px",
    gap: "16px",
    width: "285px",
    height: "40px",
    marginLeft: "-150px",
  },
  navBtnHome: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    width: "76px",
    height: "35px",
  },
  navBtnHomeContent: {
    width: "44px",
    height: "19px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "120%",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  navBtnService: {
    zIndex: "20",
    width: "auto",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "4px",
    height: "35px",
  },
  navBtnServiceContent: {
    height: "19px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "120%",
    color: "#000A2D",
  },
  navBtnAssociates: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    width: "109px",
    height: "35px",
    flex: "none",
    order: 2,
    flexGrow: 0,
  },
  navBtnAssociatesContent: {
    width: "77px",
    height: "19px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "120%",
    color: "#000A2D",
  },
  navBtnVacancy: {
    zIndex: "5",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    width: "92px",
    height: "35px",
    flex: "none",
    order: 3,
    flexGrow: 0,
  },
  navBtnVacancyContent: {
    width: "60px",
    height: "19px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "120%",
    color: "#000A2D",
  },

  navConnLoginBtnLayout: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: "0.834px",
    padding: "1px",
    width: "96px",
    height: "40.5px",
    borderRadius: "4px",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
  },
  navConnLoginBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 14px",
    width: "94.5px",
    height: "40px",
    borderRadius: "4px",
    background: "#f8f9ff",
  },
  navConnLoginBtnContent: {
    width: "34px",
    height: "auto",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "110%",
    textAlign: "center",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },

  navConnAssociateBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 14px",
    width: "175px",
    height: "40px",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    borderRadius: "4px",
  },
  navConnAssociateBtnFrame: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "0px 8px",
    gap: "8px",
    width: "147px",
    height: "16px",
  },
  navConnAssociateBtnContent: {
    width: "auto",
    height: "15px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "110%",
    textAlign: "center",
    color: "#FDFCFC",
  },
  currUserOptionsLayout: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "16px 16px 8px",
    gap: "8px",
    position: "relative",
    width: "100px",
    height: "auto",
    background: "#FFFFFF",
    borderRadius: "8px",
    zIndex: "50",
  },
  currUserOptions: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "2px 8px 8px",
    gap: "8px",
    width: "100%",
    height: "34px",
    borderBottom: "1px solid #EBEBEB",
    cursor: "pointer",
    justifyContent: "center",
  },
  currUserOptionsTxt: {
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "150%",
    color: "#000A2D",
  },
  heroLeft: {
    position: "absolute",
    width: "516.7px",
    height: "399px",
    left: "0",
    top: "0",
  },
  hero1: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "8px 16px",
    gap: "8px",
    position: "absolute",
    width: "252px",
    height: "38px",
    left: "120px",
    top: "234px",
  },
  hero1content: {
    width: "198px",
    height: "22px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "22px",
    display: "flex",
    alignItems: "center",
    color: "#363636",
  },
  hero2: {
    position: "absolute",
    display: "flex",
    width: "40px",
    height: "28.75px",
    left: "599px",
    top: "252px",
    gap: "4px",
  },
  hero3: {
    position: "absolute",
    width: "311px",
    height: "24px",
    left: "120px",
    top: "299px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    color: "#585858",
  },
  hero4: {
    position: "absolute",
    width: "510px",
    height: "132px",
    left: "120px",
    top: "331px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "44px",
    lineHeight: "150%",
    textTransform: "capitalize",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  hero4black: {
    background: "#585858",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  heroLines: {
    position: "absolute",
    width: "30px",
    height: "32px",
    right: "25px",
  },

  hero5: {
    position: "absolute",
    width: "486px",
    height: "72px",
    left: "120px",
    top: "479px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    display: "flex",
    alignItems: "center",
    color: "#636571",
  },
  heroBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 22px",
    position: "absolute",
    textDecoration: "none",
    width: "281px",
    height: "48px",
    left: "120px",
    top: "583px",
    background: "linear-gradient(90deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  heroBtnFrame: {
    display: "flex",
    flexDirection: "row",

    alignItems: "flex-start",
    padding: "0px 8px",
    gap: "8px",
  },
  heroBtnContent: {
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "100%",
    textAlign: "center",
    color: "#FDFCFC",
    paddingRight: "8px",
  },
  afterHero: {
    width: "1440px",
    height: "230px",
    margin: "76px 0 52px",
    padding: "27px 140px 27.8px 140px",
    borderRadius: "8px",
    backgroundImage: "linear-gradient(to right, #39c6ef 0%, #92cb76 109%)",
  },

  heroRight: {
    position: "absolute",
    width: "589px",
    height: "480px",
    right: "120px",
    top: "232px",
  },
  heroRightLeft: {
    position: "absolute",
    width: "589px",
    height: "480px",
    left: "120px",
    top: "232px",
  },

  heroRightStar: {
    position: "absolute",
    width: "auto",
    height: "auto",
    top: "50%",
    left: "10%",
    transform: "rotate(-105deg)",
  },
  heroMain: {
    position: "absolute",
    height: "480.7px",
    left: "143.45px",
    right: "60.8px",
    top: "0px",
    background: "rgba(24, 173, 0, 0.1)",
    opacity: 0.9,
    borderRadius: "15.2px",
  },
  heroMain1: {
    zIndex: "4",
    position: "absolute",
    width: "386.65px",
    height: "233.7px",
    left: "calc(50% - 386.65px/2 + 50.32px)",
    top: "calc(50% - 233.7px/2 + 122.55px)",
  },
  heroMain2: {
    zIndex: "3",
    position: "absolute",
    width: "372.4px",
    height: "487.35px",
    left: "22px",
    top: "calc(50% - 487.35px/2 - 2.38px)",
  },
  heroMain3: {
    zIndex: "2",
    position: "absolute",
    width: "318px",
    height: "200.59px",
    left: "-150px",
    top: "33px",
    borderRadius: "11px",
  },
  heroMain4: {
    zIndex: "1",
    position: "absolute",
    width: "379.05px",
    height: "415.15px",
    right: "-100px",
    top: "calc(50% - 415.15px/2 + 4.01px)",
  },
  dots1: {
    position: "absolute",
    left: "-3.82%",
    right: "96.13%",
    top: "40%",
    bottom: "93.08%",
  },
  dots2: {
    position: "absolute",
    left: "110%",
    top: "65%",
    bottom: "80.28%",
  },
  brief: {
    position: "absolute",
    display: "flex",
    width: "100%",
    height: "230px",
    top: "788px",
    background:
      "linear-gradient(89.56deg, rgba(57, 198, 239, 0.1) 0.38%, rgba(146, 203, 118, 0.1) 108.95%)",
    borderRadius: "8px",
  },
  briefGroup: {
    width: "1159.97px",
    height: "175.19px",
  },
  brief1: {
    position: "absolute",
    width: "346.66px",
    height: "114px",
    left: "140px",
    top: "815px",
    borderRadius: "4px",
  },
  brief1text: {
    position: "absolute",
    width: "185.47px",
    height: "33px",
    left: "80.69px",
    top: "85px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#000A2D",
  },
  brief1icon: {
    boxSizing: "border-box",
    position: "absolute",
    width: "70px",
    height: "70px",
    left: "calc(50% - 70px/2 + 0px)",
    top: "0px",
    background:
      "linear-gradient(89.56deg, rgba(57, 198, 239, 0.05) 0.38%, rgba(146, 203, 118, 0.05) 108.95%)",
    borderRadius: "4px",
  },

  brief1info: {
    position: "absolute",
    width: "282.98px",
    height: "42.59px",
    left: "31.94px",
    top: "110%",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "26px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#636571",
  },
  brief2: {
    position: "absolute",
    width: "346.66px",
    height: "114px",
    left: "42%",
    top: "815px",
    borderRadius: "4px",
  },
  brief2text: {
    position: "absolute",
    width: "237.09px",
    height: "33px",
    left: "54.87px",
    top: "85px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#000A2D",
  },
  brief2icon: {
    boxSizing: "border-box",
    position: "absolute",
    width: "70px",
    height: "70px",
    left: "calc(50% - 70px/2 - 0.01px)",
    top: "0px",
    background:
      "linear-gradient(89.56deg, rgba(57, 198, 239, 0.05) 0.38%, rgba(146, 203, 118, 0.05) 108.95%)",
    borderRadius: "4px",
  },

  brief2info: {
    position: "absolute",
    width: "282.99px",
    height: "42.59px",
    left: "31.93px",
    top: "110%",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "26px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#636571",
  },
  brief3: {
    position: "absolute",
    width: "346.66px",
    height: "114px",
    right: "140px",
    top: "815px",
    borderRadius: "4px",
  },
  brief3text: {
    position: "absolute",
    width: "235.95px",
    height: "33px",
    left: "55.46px",
    top: "85px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#000A2D",
  },
  brief3icon: {
    boxSizing: "border-box",
    position: "absolute",
    width: "70px",
    height: "70px",
    left: "calc(50% - 70px/2 + 0px)",
    top: "0px",
    background:
      "linear-gradient(89.56deg, rgba(57, 198, 239, 0.05) 0.38%, rgba(146, 203, 118, 0.05) 108.95%)",
    borderRadius: "4px",
  },

  brief3info: {
    position: "absolute",
    width: "282.98px",
    height: "42.59px",
    left: "31.94px",
    top: "110%",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "26px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#636571",
  },
  hero2leftlayout: {
    position: "absolute",
    width: "642.18px",
    height: "644.67px",
    left: "535px",
    top: "1350px",
  },
  hero2leftlayoutClose: {
    position: "absolute",
    width: "642.18px",
    height: "644.67px",
    left: "500px",
    top: "500px",
  },
  hero2leftStar: {
    zIndex: "4",
    position: "absolute",
    width: "17.14px",
    height: "22.97px",
    left: "calc(50% - 17.14px/2 - 537.06px)",
    top: "calc(50% - 22.97px/2 - 96.3px)",
  },
  hero2leftcurves: {
    zIndex: "3",
    position: "absolute",
    width: "407.17px",
    height: "322.68px",
    left: "calc(50% - 407.17px/2 - 420.42px)",
    top: "calc(50% - 322.68px/2 - 201.66px)",
  },
  hero2leftImg: {
    zIndex: "2",
    position: "absolute",
    width: "422px",
    height: "603px",
    left: "calc(50% - 422px/2 - 421.75px)",
    top: "calc(50% - 603px/2 - 281.5px)",
  },
  hero2leftcards: {
    zIndex: "1",
    position: "absolute",
    width: "600px",
    height: "800px",
    left: "-370px",
    top: "-300px",
  },
  hero2rightlayout: {
    position: "absolute",
    width: "517.68px",
    height: "390px",
    left: "752px",
    top: "1150px",
  },
  hero2rightheading: {
    position: "absolute",
    width: "438px",
    height: "117px",
    left: "220px",

    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "44px",
    lineHeight: "120%",
    textTransform: "capitalize",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  hero2rightheadingblack: {
    fontSize: "32px",
    background: "#585858",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    textFillColor: "transparent",
  },
  hero2rightpara: {
    position: "absolute",
    width: "444.43px",
    height: "68.19px",
    left: "220px",
    top: "117px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    display: "flex",
    alignItems: "center",
    color: "#636571",
  },
  hero2rightpoints: {
    position: "absolute",
    width: "517.68px",
    height: "66px",
    left: "220px",
    top: "185px",
  },
  hero2rightpt1: {
    position: "absolute",
    width: "14px",
    height: "14px",
    top: "35.81px",
  },
  hero2rightpt1text: {
    position: "absolute",
    width: "188px",
    height: "18px",
    left: "20px",
    top: "33px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "18px",
    display: "flex",
    alignItems: "center",
    color: "#000A2D",
  },

  hero2rightpt2: {
    position: "absolute",
    width: "14px",
    height: "14px",
    left: "267px",
    top: "35.81px",
  },
  hero2rightpt2text: {
    position: "absolute",
    width: "219.68px",
    height: "24px",
    left: "287px",
    top: "30px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "18px",
    display: "flex",
    alignItems: "center",
    color: "#000A2D",
  },
  hero2rightpt3: {
    position: "absolute",
    width: "14px",
    height: "14px",
    top: "82px",
  },
  hero2rightpt3text: {
    position: "absolute",
    width: "200px",
    height: "18px",
    left: "20px",
    top: "80px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "18px",
    display: "flex",
    alignItems: "center",
    color: "#000A2D",
  },
  hero2rightpt4: {
    position: "absolute",
    width: "14px",
    height: "14px",
    left: "267px",
    top: "82px",
  },
  hero2rightpt4text: {
    position: "absolute",
    width: "auto",
    height: "18px",
    left: "287px",
    top: "80px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "18px",
    display: "flex",
    alignItems: "center",
    color: "#000A2D",
  },
  hero2btn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 22px",
    position: "absolute",
    width: "281px",
    height: "48px",
    left: "217px",
    top: "320px",
    background: "linear-gradient(90deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  hero2btncontent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "0px 8px",
    gap: "8px",
    width: "83px",
    height: "16px",
  },
  hero2btntext: {
    width: "67px",
    height: "16px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "100%",
    textAlign: "center",
    color: "#FDFCFC",
    marginRight: "15px",
  },
  testimonialsLayout: {
    position: "absolute",
    width: "100%",
    height: "528px",
    left: "0px",
    top: "1669px",
  },
  testimonialsBackground: {
    position: "absolute",
    width: "100%",
    height: "528px",
    left: "0px",
    top: "23px",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    borderRadius: "8px",
  },
  testimonialsMain: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "0px",
    gap: "160px",
    position: "absolute",
    width: "1300px",
    height: "305px",
    left: "200px",
    top: "calc(50% - 320px/2 - 0.5px)",
  },
  testimonialsLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "0px",
    gap: "24px",
    width: "502px",
    height: "182px",
  },

  testimonialsLeftText: {
    width: "480px",
    height: "106px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 800,
    fontSize: "44px",
    lineHeight: "53px",
    color: "#021526",
  },
  testimonialsLeftTextBlue: {
    color: "#0360D9",
  },
  testimonialsAvatar: {
    position: "absolute",
    width: "368px",
    height: "52px",
    top: "19%",
  },
  testimonialsAv1: {
    position: "absolute",
    width: "52px",
    height: "52px",
    left: "0px",
    top: "130px",
  },
  testimonialsAv2: {
    position: "absolute",
    width: "53px",
    height: "52px",
    left: "34px",
    top: "130px",
  },
  testimonialsAv3: {
    position: "absolute",
    width: "52px",
    height: "52px",
    left: "69px",
    top: "130px",
  },
  testimonialsAv4: {
    position: "absolute",
    width: "52px",
    height: "52px",
    left: "103px",
    top: "130px",
  },
  testimonialsAv5: {
    position: "absolute",
    width: "53px",
    height: "52px",
    left: "137px",
    top: "130px",
  },
  testimonialsAv6: {
    position: "absolute",
    width: "52px",
    height: "52px",
    left: "172px",
    top: "130px",
  },
  testimonialsAvText: {
    position: "absolute",
    width: "117px",
    height: "19px",
    left: "251px",
    top: "145px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#2E2E2E",
  },
  testimonialsRight: {
    boxSizing: "border-box",
    position: "absolute",
    width: "590px",
    height: "305px",
    right: "0px",
    top: "0px",
    background: "#FFFFFF",
    border: "1px solid #A8A8A8",
    borderRadius: "20px",
  },
  testimonialsRightTextLayout: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "0px",
    gap: "5px",
    position: "absolute",
    width: "494px",
    height: "113px",

    left: "49px",
    top: "143px",
  },
  testimonialsRightTextHeading: {
    width: "494px",
    height: "36px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "150%",
    color: "#2E2E2E",
  },
  testimonialsRightTextPara: {
    width: "494px",
    height: "72px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    color: "#2E2E2E",
  },
  testimonialsRightAv: {
    position: "absolute",
    width: "52px",
    height: "52px",
    left: "49px",
    top: "49px",
  },
  testimonialsRightAvName: {
    position: "absolute",
    width: "132px",
    height: "19px",
    left: "115px",
    top: "54px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19px",
    color: "#2E2E2E",
  },
  testimonialsRightAvDate: {
    position: "absolute",
    width: "132px",
    height: "14px",
    left: "115px",
    top: "78px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "14px",
    color: "#2E2E2E",
  },
  testimonialsRightStar1: {
    position: "absolute",
    width: "40px",
    height: "40px",
    left: "500px",
    top: "54px",
  },
  testimonialsRightStar2: {
    position: "absolute",
    width: "40px",
    height: "40px",
    left: "450px",
    top: "54px",
  },
  testimonialsRightStar3: {
    position: "absolute",
    width: "40px",
    height: "40px",
    left: "400px",
    top: "54px",
  },
  testimonialsRightStar4: {
    position: "absolute",
    width: "40px",
    height: "40px",
    left: "350px",
    top: "54px",
  },
  testimonialsRightStar5: {
    position: "absolute",
    width: "40px",
    height: "40px",
    left: "300px",
    top: "54px",
  },
  thumb1: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "120px",
    top: "20px",
  },
  thumb1back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "120px",
    top: "2260px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb1text: {
    position: "absolute",
    width: "234px",
    height: "29px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb2: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "424px",
    top: "20px",
  },

  thumb2back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "120px",
    top: "2260px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb2text: {
    position: "absolute",
    width: "234px",
    height: "29px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb3: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "444px",
    top: "20px",
  },
  thumb3back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "405px",
    top: "2260px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb3text: {
    position: "absolute",
    width: "234px",
    height: "29px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },

  thumb4: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "520px",
    top: "20px",
  },
  thumb4back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "635px",
    top: "2260px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb4text: {
    position: "absolute",
    width: "234px",
    height: "29px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb5: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "120px",
    top: "322px",
  },
  thumb5back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "120px",
    top: "2265px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb5text: {
    position: "absolute",
    width: "234px",
    height: "58px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb6: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "424px",
    top: "322px",
  },
  thumb6back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "120px",
    top: "2265px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb6text: {
    position: "absolute",
    width: "234px",
    height: "58px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb7: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "444px",
    top: "322px",
  },
  thumb7back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "405px",
    top: "2265px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb7text: {
    position: "absolute",
    width: "234px",
    height: "58px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  thumb8: {
    position: "absolute",
    width: "283px",
    height: "282px",
    left: "1035px",
    top: "322px",
  },
  thumb8back: {
    position: "absolute",
    width: "282px",
    height: "282px",
    left: "120px",
    top: "2265px",
    background: "linear-gradient(180deg, #39C6EF 0%, #92CB76 100%)",
    borderRadius: "8px",
  },
  thumb8text: {
    position: "absolute",
    width: "234px",
    height: "58px",
    left: "18px",
    top: "130px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "29px",
    textAlign: "center",
    color: "#FFFFFF",
  },
  footer: {
    position: "absolute",
    width: "100%",
    height: "396px",
    left: "0px",
    top: "2910px",
    background: "#000A2D",
    color: "black",
  },
  footerSignup: {
    position: "absolute",
    width: "100%",
    height: "396px",
    left: "0px",
    top: "1000px",
    background: "#000A2D",
  },
  footerLogin: {
    position: "absolute",
    width: "100%",
    height: "396px",
    left: "0px",
    top: "842.25px",
    background: "#000A2D",
  },
  footer1: {
    position: "absolute",

    width: "282px",
    height: "225px",
    left: "119px",
    top: "65px",
  },
  footer1logo: {
    position: "absolute",
    width: "218px",
    height: "63px",
    left: "119px",
  },
  footer1text: {
    position: "absolute",
    width: "282px",
    height: "96px",
    left: "119px",
    top: "75px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    color: "#FFFFFF",
  },
  footer1social: {
    position: "absolute",
    display: "flex",
    width: "94.34px",
    height: "21px",
    left: "120px",
    top: "190px",
    gap: "20px",
  },
  footer2: {
    position: "absolute",
    width: "137px",
    height: "218.39px",
    left: "450.98px",
    top: "68px",
  },
  footer2head: {
    position: "absolute",
    width: "131.37px",
    height: "30px",
    left: "150px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "22px",
    lineHeight: "26px",
    display: "flex",
    alignItems: "center",
    color: "#FFFFFF",
  },
  footer2divider: {
    boxSizing: "border-box",
    position: "absolute",
    width: "80px",
    height: "2px",
    background: "white",
    left: "150px",
    top: "42px",
    backgroundImage:
      "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
  },
  footer2a: {
    position: "absolute",
    width: "52px",
    height: "19px",
    left: "150px",
    top: "75px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer2b: {
    position: "absolute",
    width: "66px",
    height: "19px",
    left: "150px",
    top: "112px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer2c: {
    position: "absolute",
    width: "98px",
    height: "19px",
    left: "150px",
    top: "145px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer2d: {
    position: "absolute",
    width: "137px",
    height: "19px",
    left: "150px",
    top: "178px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer3: {
    position: "absolute",
    width: "176.25px",
    height: "221.39px",
    left: "719.75px",
    top: "68px",
  },
  footer3a: {
    position: "absolute",
    width: "117px",
    height: "19px",
    left: "150px",
    top: "75px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer3b: {
    position: "absolute",
    width: "155px",
    height: "19px",
    left: "150px",
    top: "112px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer3c: {
    position: "absolute",
    width: "174px",
    height: "19px",
    left: "150px",
    top: "145px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer3d: {
    position: "absolute",
    width: "200px",
    height: "19px",
    left: "150px",
    top: "178px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer4: {
    position: "absolute",
    width: "344.25px",
    height: "229px",
    left: "975.75px",
    top: "68px",
  },
  footer4heading: {
    position: "absolute",
    width: "344px",
    height: "57px",
    top: "75px",
    left: "150px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "24px",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.9)",
  },
  footer4inputlayout: {
    position: "absolute",
    height: "50px",
    width: "100%",
    right: "120px",
    left: "150px",
    bottom: "30px",
    background: "#FFFFFF",
    borderRadius: "4px",
  },
  footer4input: {
    width: "100%",
    height: "100%",
    border: "none",
    borderRadius: "4px",
  },
  footer4inputbtn: {
    zIndex: "5",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "6px 34.39px 6px 32.61px",
    position: "absolute",
    height: "31px",
    left: "222px",
    top: "calc(50% - 42px/2)",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    borderRadius: "5px",
  },
  footer4inputbtntext: {
    paddingTop: "7px",
    width: "55px",
    height: "19px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#FFFFFF",
  },
  footerBottom: {
    position: "absolute",
    width: "1200px",
    height: "36.5px",
    left: "120px",
    top: "337.5px",
  },
  footerBottomLine: {
    position: "absolute",
    width: "1200px",
    height: "0px",
    left: "120px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  footerBottomLeft: {
    position: "absolute",
    width: "236px",
    height: "17px",
    left: "120px",
    top: "18px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "17px",
    color: "#FFFFFF",
  },
  footerBottomRight: {
    position: "absolute",
    width: "118px",
    height: "17px",
    left: "1202px",
    top: "18px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "17px",
    textAlign: "right",
    color: "#FFFFFF",
  },
};
