export const formStyles = {
  logo: {
    position: "absolute",
    width: "204px",
    height: "56px",
    left: "119px",
    top: "135px",
  },
  header: {
    position: "absolute",
    width: "auto",
    height: "36px",
    left: "943px",
    top: "145px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "30px",
    lineHeight: "36px",
    display: "flex",
    alignItems: "center",
    color: "#000000",
  },
  desc: {
    position: "absolute",
    width: "411px",
    height: "56px",
    left: "943px",
    top: "191px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "28px",
    display: "flex",
    alignItems: "center",
    color: "#8692A6",
  },
  formLayout: {
    position: "absolute",
    width: "426px",
    height: "246px",
    left: "943px",
    top: "345px",
  },
  labelname: {
    position: "absolute",
    width: "117px",
    height: "19px",
    left: "0px",
    top: "-50px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  inputname: {
    boxSizing: "border-box",
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    fontFamily: "'Lato'",
    top: "50px",
    border: "1px solid #8692A6",
    borderRadius: "6px",
    paddingLeft: "30px",
  },

  labelemail: {
    position: "absolute",
    width: "117px",
    height: "19px",
    left: "0px",
    top: "90px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  inputemail: {
    boxSizing: "border-box",
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    fontFamily: "'Lato'",
    top: "50px",
    border: "1px solid #8692A6",
    borderRadius: "6px",
    paddingLeft: "30px",
  },
  labelnumber: {
    position: "absolute",
    width: "117px",
    height: "19px",
    left: "0px",
    top: "230px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  inputnumber: {
    boxSizing: "border-box",
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    fontFamily: "'Lato'",
    top: "50px",
    border: "1px solid #8692A6",
    borderRadius: "6px",
    paddingLeft: "30px",
  },
  labelpass: {
    position: "absolute",
    width: "129px",
    height: "19px",
    left: "0px",
    top: "370px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  inputpass: {
    boxSizing: "border-box",
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    fontFamily: "'Lato'",
    top: "50px",
    border: "1px solid #8692A6",
    borderRadius: "6px",
    paddingLeft: "30px",
  },
  sbmtBtn: {
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    top: "230px",
    border: "none",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    borderRadius: "8px",
  },
  sbmtBtn2: {
    position: "absolute",
    width: "426px",
    height: "64px",
    left: "0px",
    top: "547px",
    border: "none",
    background: "linear-gradient(89.56deg, #39C6EF 0.38%, #92CB76 108.95%)",
    borderRadius: "8px",
  },
  btnTxt: {
    position: "absolute",
    width: "auto",
    height: "19px",
    left: "195px",
    top: "23px",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#FFFFFF",
  },
  inputCheckbox: {
    position: "absolute",
    width: "20px",
    height: "20px",
    left: "-30px",
    top: "0px",
  },
  checkboxlabel: {
    position: "absolute",
    width: "220px",
    height: "19px",
    left: "30px",
    top: "235px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  checkboxlabel2: {
    position: "absolute",
    width: "220px",
    height: "19px",
    left: "30px",
    top: "510px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
  signupRedirect: {
    position: "absolute",
    width: "auto",
    height: "19px",
    left: "0px",
    top: "320px",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
    zIndex: "8",
  },
  loginRedirect: {
    position: "absolute",
    width: "auto",
    height: "19px",
    left: "0px",
    top: "627px",
    fontFamily: "'Lato'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "19px",
    display: "flex",
    alignItems: "center",
    color: "#696F79",
  },
};
